### ISSUE TITLE
Server parameter requires full URI when port specified.

### ISSUE THREAD

**Issue by Denney-tech** [jborean93/PSOpenAD#12]
If I want to use a specific server in an implicit session, I can specify the server name and everything is fine.  Default behavior (I assume) is to use the standard 389/636 ldap(s) ports, just like Microsoft's AD module.  If I wanted to use a global catalog however, I'd need to specify ports 3268/3269.  When I do this on Windows with AD cmdlets, I only need to specify server_name:port_number, but with PSOpenAD I need to specify the full ldap(s)://uri, global catalog or not.

``` powershell
PS /> Get-OpenADComputer $env:HOSTNAME -Server dca.contoso.com:389
```
`Get-OpenADComputer: Invalid URI: Invalid port specified`
Specifying server name without a port works fine without the full uri given.

**Comment by jborean93** [comment]
Sounds like a good idea, shouldn't be too hard to do.
