### ISSUE TITLE
Credential Parameter should prompt

### ISSUE THREAD

**Issue by jdhitsolutions** [jborean93/PSOpenAD#24]
In PowerShell, you can specify the username as part of a Credential parameter, and PowerShell will prompt for the password.

![image](https://user-images.githubusercontent.com/12089920/173409658-ca6af119-ff2b-422f-adde-7e2d4f45917d.png)

But this behavior isn't supported in `New-OpenADSession`. I haven't tried anything else yet.

![image](https://user-images.githubusercontent.com/12089920/173409751-01e26357-f6a7-47f7-8f55-bff885b2296c.png)

**Comment by jborean93** [comment]
Thanks for pointing that out, looks like I need to add the `[Credential()]` attribute to this parameter at https://github.com/jborean93/PSOpenAD/blob/main/src/Commands/OpenADSession.cs#L60.
