### ISSUE TITLE
Authentication issue crashes PowerShell session

### ISSUE THREAD

**Issue by jdhitsolutions** [jborean93/PSOpenAD#26]
I was testing `New-OpenADSession` and I realize authentication needs to be included, but it should handle the error a bit more gracefully. When I run this in a PS 7 session running in Windows Terminal on Windows 11, it crashes the session.

![image](https://user-images.githubusercontent.com/12089920/173432632-6da380cd-ab66-46e6-bdd9-5c99beb616e6.png)

I'm assuming you would prefer something a bit less traumatic.

**Comment by jborean93** [comment]
Hmm, looks like I might need some better checks to only dispose the SSPI context if it was actually set. Will play around with this to try and verify and fix.

**Comment by jborean93** [comment]
Oh and Authentication shouldn't be required, it should be defaulting to `Negotiate` on Windows. Is the auth unsuccessful without `-Authentication ...`?

**Comment by jborean93** [comment]
Ah actually this has already been fixed with https://github.com/jborean93/PSOpenAD/pull/18. The next preview will include these changes and I'm planning on putting it out sometime in the comming days.

**Comment by jdhitsolutions** [comment]
Ok.
