### ISSUE TITLE
Running command is not responding

### ISSUE THREAD

**Issue by crimsonread** [jborean93/PSOpenAD#43]
Hello,

Generally, This module is okay but some times after importing module,
Running command is not responding.
In order to solve it,  **Import-Module PSOpenAD -Force**
The problem is this issue keep happening.

PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by jborean93** [comment]
I do have a few questions

* is it always straight after importing or just over time
* are you running a particular command, if so what one and with what parameters
* what type of auth are you using, explicit creds or not?
* when you say it hangs, how do you then reimport the module

Essentially I’m trying to figure out what your workflow is so I can try and replicate it. The more information you can give me the more likely it is I can find the problem.

**Comment by crimsonread** [comment]
> 

1) It happens that some over time after importing module. I cannot specify how long it takes though. (maybe over 10minutes)
2) I used Get-OpenADComputer/Get-OpenADUser.
3) I did not used explicit credential.
4) I just used **Ctrl+C** to cancel process and reimport module again.

Thanks.

**Comment by jborean93** [comment]
> It happens that some over time after importing module. I cannot specify how long it takes though. (maybe over 10minutes)

This is the part that’s not clear to me. Is it failing on the first command after the import or you import it, run some commands and eventually it hangs?

**Comment by crimsonread** [comment]
It looks that only happen when I was away for more than 15~20 minutes which do not input anything on powershell console. Apart from that situation, it is okay.

**Comment by jborean93** [comment]
I've been able to reproduce this error. It looks like after a set amount of time the connection is dropped on the TCP level and the code in the module needs to handle this appropriately rather than just hang. Will have to play around with this some more to figure out a good solution.

**Comment by jborean93** [comment]
The PR https://github.com/jborean93/PSOpenAD/pull/45 solves this issue https://github.com/jborean93/PSOpenAD/pull/45. When a connection is timed out it will be properly marked as closed and no longer re-used in the global cache. Keep in mind if you do have an explicit session created with `New-OpenADSession` and the connection is reset it will still fail the next time it is used but it will not hang. In your scenario you are relying on the session cache so this should not be an issue for you.
