### ISSUE TITLE
Get-OpenADUser erroring because contacts don't have sid/SAMAccountName

### ISSUE THREAD

**Issue by john-heasman-cg** [jborean93/PSOpenAD#44]
I am running Get-OpenADUser to get a list of users and it is erroring after receiving a few records with:

`Get-OpenADUser: sid`

It looks like this is because the default query for this command is "(objectCategory=person)" and this is pulling back both users AND contacts, and contacts don't have a sid/SAMAccountName.

[This article](https://docs.microsoft.com/en-us/windows/win32/ad/querying-for-users) states the query for retrieving users should be:

`(&(objectClass=user)(objectCategory=person))`

A workaround is therefore to run:

`Get-OpenADUser -LDAPFilter "(objectclass=user)"`

... but you might want to modify the default query.

Thanks & great work on this module, it is incredibly useful!

**Comment by jborean93** [comment]
Thanks for the info, it should be simple to adjust the default query to also include `(objectClass=user)` as part of the original set. I'll have a play around with contacts to see how the MS `Get-ADUser` module handles them but it does seem like it avoids them.
