### ISSUE TITLE
-Property is case-sensitive

### ISSUE THREAD

**Issue by theaquamarine** [jborean93/PSOpenAD#51]
I'm not sure if this is intentional, but reporting it as it feels like a step backwards vs ActiveDirectory: Requesting specific attributes with `-Property` is case-sensitive in PSOpenAD. With #41 merged, it's also not always obvious what the correct casing is, particularly for more complex attribute names like `ms-Mcs-AdmPwd`.

eg

```
Get-OpenADComputer testcomputer -Property Name
# Get-OpenADComputer: One or more properties for computer are not valid: 'Name'
```

vs `Get-OpenADComputer testcomputer -Property name` and `Get-ADComputer testcomputer -Property Name` working.

**Comment by jborean93** [comment]
Scratch that sorry I had an older version installed on my test host. I can see this problem and will dig deeper as it should not be case sensitive.

**Comment by jborean93** [comment]
The PR https://github.com/jborean93/PSOpenAD/pull/52 should fix this to go back to the case insensitive comparisons.

**Comment by theaquamarine** [comment]
Yep, that's fixed it for me. Thanks very much!
