### ISSUE TITLE
Change Get-OpenADComputer -Identity filter (Linux)

### ISSUE THREAD

**Issue by Denney-tech** [jborean93/PSOpenAD#6]
`Get-OpenADComputer $env:HOSTNAME` fails to find any results because -Identity is filtering by sAMAccountName when it should filter by Name.  Computers in Active Directory have trailing dollar signs '$' in the SamAccountName property; the Name property does not.

The workaround is of course to use `Get-OpenADComputer -LDAPFilter "Name=$env:HOSTNAME"`, but this is inconsistent behavior with its `Get-ADComputer $env:ComputerName` counterpart.

Tested on:
  - OS: Fedora 35
  - PowerShell: 7.2.1
  - PSOpenAD: 0.1.0 preview1
  - Microsoft Active Directory session

**Comment by jborean93** [comment]
That's interesting, the documentation for `Get-ADComputer` states that `-Identity` can be the `DN`, `objectGUID`, `objectSid`, or `sAMAccountName` and not the `name` attribute. I wonder if it still looks like `sAMAccountName` but just adds the end `$` as a convenience if it's not already there. Will have to do some testing to verify.

**Comment by jborean93** [comment]
Can confirm it's still looking up based on the `sAMAccountName` and it's just adding the `$` suffix if it's not already there. I used `New-ADComputer` to create a computer object with the `name` of `ComputerName` and a `sAMAccountName` of `ComputerSAM` and `Get-ADComputer -Identity` only worked with the `sAMAccountName`. It shouldn't be too difficult to implement here.

**Comment by Denney-tech** [comment]
Ah, I see. I hadn't considered they could be different; I'm just used to being able to search by hostname or piping a list of hostnames.
